# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: efficient_paper.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='efficient_paper.proto',
  package='efficient_paper',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x65\x66\x66icient_paper.proto\x12\x0f\x65\x66\x66icient_paper\"\xf9\x01\n\tPaperInfo\x12%\n\x05paper\x18\x01 \x01(\x0b\x32\x16.efficient_paper.Paper\x12)\n\x03pub\x18\x02 \x01(\x0b\x32\x1c.efficient_paper.Publication\x12#\n\x04\x63ode\x18\x03 \x01(\x0b\x32\x15.efficient_paper.Code\x12#\n\x04note\x18\x04 \x01(\x0b\x32\x15.efficient_paper.Note\x12)\n\x07keyword\x18\x05 \x01(\x0b\x32\x18.efficient_paper.Keyword\x12%\n\x05\x63over\x18\x06 \x01(\x0b\x32\x16.efficient_paper.Cover\"k\n\x05Paper\x12\x1a\n\x05title\x18\x01 \x01(\t:\x0bpaper title\x12\x12\n\x04\x61\x62\x62r\x18\x02 \x01(\t:\x04\x61\x62\x62r\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x0f\n\x07\x61uthors\x18\x04 \x03(\t\x12\x14\n\x0cinstitutions\x18\x05 \x03(\t\"*\n\x0bPublication\x12\r\n\x05where\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05\"*\n\x04\x43ode\x12\x15\n\x04type\x18\x01 \x01(\t:\x07Pytorch\x12\x0b\n\x03url\x18\x02 \x01(\t\"\x13\n\x04Note\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x14\n\x05\x43over\x12\x0b\n\x03url\x18\x01 \x01(\t\"{\n\x07Keyword\x12,\n\x05words\x18\x01 \x03(\x0e\x32\x1d.efficient_paper.Keyword.Word\"B\n\x04Word\x12\x08\n\x04none\x10\x01\x12\x12\n\x0esparse_pruning\x10\x02\x12\x10\n\x0cquantization\x10\x03\x12\n\n\x06survey\x10\x04')
)



_KEYWORD_WORD = _descriptor.EnumDescriptor(
  name='Word',
  full_name='efficient_paper.Keyword.Word',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='none', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sparse_pruning', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='quantization', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='survey', index=3, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=591,
  serialized_end=657,
)
_sym_db.RegisterEnumDescriptor(_KEYWORD_WORD)


_PAPERINFO = _descriptor.Descriptor(
  name='PaperInfo',
  full_name='efficient_paper.PaperInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='paper', full_name='efficient_paper.PaperInfo.paper', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pub', full_name='efficient_paper.PaperInfo.pub', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='efficient_paper.PaperInfo.code', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='note', full_name='efficient_paper.PaperInfo.note', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keyword', full_name='efficient_paper.PaperInfo.keyword', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cover', full_name='efficient_paper.PaperInfo.cover', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=292,
)


_PAPER = _descriptor.Descriptor(
  name='Paper',
  full_name='efficient_paper.Paper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='efficient_paper.Paper.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("paper title").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='abbr', full_name='efficient_paper.Paper.abbr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("abbr").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='efficient_paper.Paper.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authors', full_name='efficient_paper.Paper.authors', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='institutions', full_name='efficient_paper.Paper.institutions', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=401,
)


_PUBLICATION = _descriptor.Descriptor(
  name='Publication',
  full_name='efficient_paper.Publication',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='where', full_name='efficient_paper.Publication.where', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='year', full_name='efficient_paper.Publication.year', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=445,
)


_CODE = _descriptor.Descriptor(
  name='Code',
  full_name='efficient_paper.Code',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='efficient_paper.Code.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("Pytorch").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='efficient_paper.Code.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=447,
  serialized_end=489,
)


_NOTE = _descriptor.Descriptor(
  name='Note',
  full_name='efficient_paper.Note',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='efficient_paper.Note.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=510,
)


_COVER = _descriptor.Descriptor(
  name='Cover',
  full_name='efficient_paper.Cover',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='efficient_paper.Cover.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=512,
  serialized_end=532,
)


_KEYWORD = _descriptor.Descriptor(
  name='Keyword',
  full_name='efficient_paper.Keyword',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='words', full_name='efficient_paper.Keyword.words', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _KEYWORD_WORD,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=534,
  serialized_end=657,
)

_PAPERINFO.fields_by_name['paper'].message_type = _PAPER
_PAPERINFO.fields_by_name['pub'].message_type = _PUBLICATION
_PAPERINFO.fields_by_name['code'].message_type = _CODE
_PAPERINFO.fields_by_name['note'].message_type = _NOTE
_PAPERINFO.fields_by_name['keyword'].message_type = _KEYWORD
_PAPERINFO.fields_by_name['cover'].message_type = _COVER
_KEYWORD.fields_by_name['words'].enum_type = _KEYWORD_WORD
_KEYWORD_WORD.containing_type = _KEYWORD
DESCRIPTOR.message_types_by_name['PaperInfo'] = _PAPERINFO
DESCRIPTOR.message_types_by_name['Paper'] = _PAPER
DESCRIPTOR.message_types_by_name['Publication'] = _PUBLICATION
DESCRIPTOR.message_types_by_name['Code'] = _CODE
DESCRIPTOR.message_types_by_name['Note'] = _NOTE
DESCRIPTOR.message_types_by_name['Cover'] = _COVER
DESCRIPTOR.message_types_by_name['Keyword'] = _KEYWORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PaperInfo = _reflection.GeneratedProtocolMessageType('PaperInfo', (_message.Message,), dict(
  DESCRIPTOR = _PAPERINFO,
  __module__ = 'efficient_paper_pb2'
  # @@protoc_insertion_point(class_scope:efficient_paper.PaperInfo)
  ))
_sym_db.RegisterMessage(PaperInfo)

Paper = _reflection.GeneratedProtocolMessageType('Paper', (_message.Message,), dict(
  DESCRIPTOR = _PAPER,
  __module__ = 'efficient_paper_pb2'
  # @@protoc_insertion_point(class_scope:efficient_paper.Paper)
  ))
_sym_db.RegisterMessage(Paper)

Publication = _reflection.GeneratedProtocolMessageType('Publication', (_message.Message,), dict(
  DESCRIPTOR = _PUBLICATION,
  __module__ = 'efficient_paper_pb2'
  # @@protoc_insertion_point(class_scope:efficient_paper.Publication)
  ))
_sym_db.RegisterMessage(Publication)

Code = _reflection.GeneratedProtocolMessageType('Code', (_message.Message,), dict(
  DESCRIPTOR = _CODE,
  __module__ = 'efficient_paper_pb2'
  # @@protoc_insertion_point(class_scope:efficient_paper.Code)
  ))
_sym_db.RegisterMessage(Code)

Note = _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), dict(
  DESCRIPTOR = _NOTE,
  __module__ = 'efficient_paper_pb2'
  # @@protoc_insertion_point(class_scope:efficient_paper.Note)
  ))
_sym_db.RegisterMessage(Note)

Cover = _reflection.GeneratedProtocolMessageType('Cover', (_message.Message,), dict(
  DESCRIPTOR = _COVER,
  __module__ = 'efficient_paper_pb2'
  # @@protoc_insertion_point(class_scope:efficient_paper.Cover)
  ))
_sym_db.RegisterMessage(Cover)

Keyword = _reflection.GeneratedProtocolMessageType('Keyword', (_message.Message,), dict(
  DESCRIPTOR = _KEYWORD,
  __module__ = 'efficient_paper_pb2'
  # @@protoc_insertion_point(class_scope:efficient_paper.Keyword)
  ))
_sym_db.RegisterMessage(Keyword)


# @@protoc_insertion_point(module_scope)
